pub fn key_to_code(key: &rdev::Key) -> Option<&'static str> {
    use rdev::Key::*;

    match key {
        Escape => Some("Escape"),
        F1 => Some("F1"),
        F2 => Some("F2"),
        F3 => Some("F3"),
        F4 => Some("F4"),
        F5 => Some("F5"),
        F6 => Some("F6"),
        F7 => Some("F7"),
        F8 => Some("F8"),
        F9 => Some("F9"),
        F10 => Some("F10"),
        F11 => Some("F11"),
        F12 => Some("F12"),
        BackQuote => Some("Backquote"),
        Num1 => Some("Digit1"),
        Num2 => Some("Digit2"),
        Num3 => Some("Digit3"),
        Num4 => Some("Digit4"),
        Num5 => Some("Digit5"),
        Num6 => Some("Digit6"),
        Num7 => Some("Digit7"),
        Num8 => Some("Digit8"),
        Num9 => Some("Digit9"),
        Num0 => Some("Digit0"),
        Minus => Some("Minus"),
        Equal => Some("Equal"),
        Backspace => Some("Backspace"),
        KeyQ => Some("KeyQ"),
        KeyW => Some("KeyW"),
        KeyE => Some("KeyE"),
        KeyR => Some("KeyR"),
        KeyT => Some("KeyT"),
        KeyY => Some("KeyY"),
        KeyU => Some("KeyU"),
        KeyI => Some("KeyI"),
        KeyO => Some("KeyO"),
        KeyP => Some("KeyP"),
        LeftBracket => Some("BracketLeft"),
        RightBracket => Some("BracketRight"),
        BackSlash => Some("Backslash"),
        CapsLock => Some("CapsLock"),
        KeyA => Some("KeyA"),
        KeyS => Some("KeyS"),
        KeyD => Some("KeyD"),
        KeyF => Some("KeyF"),
        KeyG => Some("KeyG"),
        KeyH => Some("KeyH"),
        KeyJ => Some("KeyJ"),
        KeyK => Some("KeyK"),
        KeyL => Some("KeyL"),
        SemiColon => Some("Semicolon"),
        Quote => Some("Quote"),
        Return => Some("Enter"),
        ShiftLeft => Some("ShiftLeft"),
        KeyZ => Some("KeyZ"),
        KeyX => Some("KeyX"),
        KeyC => Some("KeyC"),
        KeyV => Some("KeyV"),
        KeyB => Some("KeyB"),
        KeyN => Some("KeyN"),
        KeyM => Some("KeyM"),
        Comma => Some("Comma"),
        Dot => Some("Period"),
        Slash => Some("Slash"),
        ShiftRight => Some("ShiftRight"),
        ControlLeft => Some("ControlLeft"),
        Alt => Some("AltLeft"),
        Space => Some("Space"),
        AltGr => Some("AltRight"),
        ControlRight => Some("ControlRight"),
        Tab => Some("Tab"),
        Delete => Some("Delete"),
        Home => Some("Home"),
        End => Some("End"),
        PageUp => Some("PageUp"),
        PageDown => Some("PageDown"),
        UpArrow => Some("ArrowUp"),
        DownArrow => Some("ArrowDown"),
        LeftArrow => Some("ArrowLeft"),
        RightArrow => Some("ArrowRight"),
        Kp0 => Some("Numpad0"),
        Kp1 => Some("Numpad1"),
        Kp2 => Some("Numpad2"),
        Kp3 => Some("Numpad3"),
        Kp4 => Some("Numpad4"),
        Kp5 => Some("Numpad5"),
        Kp6 => Some("Numpad6"),
        Kp7 => Some("Numpad7"),
        Kp8 => Some("Numpad8"),
        Kp9 => Some("Numpad9"),
        KpMinus => Some("NumpadSubtract"),
        KpPlus => Some("NumpadAdd"),
        KpMultiply => Some("NumpadMultiply"),
        KpDivide => Some("NumpadDivide"),
        KpDelete => Some("NumpadDecimal"),
        KpReturn => Some("NumpadEnter"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::key_to_code;
    use rdev::Key;

    #[test]
    fn maps_supported_keys_to_browser_codes() {
        let cases = [
            (Key::Escape, "Escape"),
            (Key::F1, "F1"),
            (Key::F2, "F2"),
            (Key::F3, "F3"),
            (Key::F4, "F4"),
            (Key::F5, "F5"),
            (Key::F6, "F6"),
            (Key::F7, "F7"),
            (Key::F8, "F8"),
            (Key::F9, "F9"),
            (Key::F10, "F10"),
            (Key::F11, "F11"),
            (Key::F12, "F12"),
            (Key::BackQuote, "Backquote"),
            (Key::Num1, "Digit1"),
            (Key::Num2, "Digit2"),
            (Key::Num3, "Digit3"),
            (Key::Num4, "Digit4"),
            (Key::Num5, "Digit5"),
            (Key::Num6, "Digit6"),
            (Key::Num7, "Digit7"),
            (Key::Num8, "Digit8"),
            (Key::Num9, "Digit9"),
            (Key::Num0, "Digit0"),
            (Key::Minus, "Minus"),
            (Key::Equal, "Equal"),
            (Key::Backspace, "Backspace"),
            (Key::KeyQ, "KeyQ"),
            (Key::KeyW, "KeyW"),
            (Key::KeyE, "KeyE"),
            (Key::KeyR, "KeyR"),
            (Key::KeyT, "KeyT"),
            (Key::KeyY, "KeyY"),
            (Key::KeyU, "KeyU"),
            (Key::KeyI, "KeyI"),
            (Key::KeyO, "KeyO"),
            (Key::KeyP, "KeyP"),
            (Key::LeftBracket, "BracketLeft"),
            (Key::RightBracket, "BracketRight"),
            (Key::BackSlash, "Backslash"),
            (Key::CapsLock, "CapsLock"),
            (Key::KeyA, "KeyA"),
            (Key::KeyS, "KeyS"),
            (Key::KeyD, "KeyD"),
            (Key::KeyF, "KeyF"),
            (Key::KeyG, "KeyG"),
            (Key::KeyH, "KeyH"),
            (Key::KeyJ, "KeyJ"),
            (Key::KeyK, "KeyK"),
            (Key::KeyL, "KeyL"),
            (Key::SemiColon, "Semicolon"),
            (Key::Quote, "Quote"),
            (Key::Return, "Enter"),
            (Key::ShiftLeft, "ShiftLeft"),
            (Key::KeyZ, "KeyZ"),
            (Key::KeyX, "KeyX"),
            (Key::KeyC, "KeyC"),
            (Key::KeyV, "KeyV"),
            (Key::KeyB, "KeyB"),
            (Key::KeyN, "KeyN"),
            (Key::KeyM, "KeyM"),
            (Key::Comma, "Comma"),
            (Key::Dot, "Period"),
            (Key::Slash, "Slash"),
            (Key::ShiftRight, "ShiftRight"),
            (Key::ControlLeft, "ControlLeft"),
            (Key::Alt, "AltLeft"),
            (Key::Space, "Space"),
            (Key::AltGr, "AltRight"),
            (Key::ControlRight, "ControlRight"),
            (Key::Tab, "Tab"),
            (Key::Delete, "Delete"),
            (Key::Home, "Home"),
            (Key::End, "End"),
            (Key::PageUp, "PageUp"),
            (Key::PageDown, "PageDown"),
            (Key::UpArrow, "ArrowUp"),
            (Key::DownArrow, "ArrowDown"),
            (Key::LeftArrow, "ArrowLeft"),
            (Key::RightArrow, "ArrowRight"),
            (Key::Kp0, "Numpad0"),
            (Key::Kp1, "Numpad1"),
            (Key::Kp2, "Numpad2"),
            (Key::Kp3, "Numpad3"),
            (Key::Kp4, "Numpad4"),
            (Key::Kp5, "Numpad5"),
            (Key::Kp6, "Numpad6"),
            (Key::Kp7, "Numpad7"),
            (Key::Kp8, "Numpad8"),
            (Key::Kp9, "Numpad9"),
            (Key::KpMinus, "NumpadSubtract"),
            (Key::KpPlus, "NumpadAdd"),
            (Key::KpMultiply, "NumpadMultiply"),
            (Key::KpDivide, "NumpadDivide"),
            (Key::KpDelete, "NumpadDecimal"),
            (Key::KpReturn, "NumpadEnter"),
        ];

        for (key, expected) in cases {
            assert_eq!(
                key_to_code(&key),
                Some(expected),
                "unexpected browser code for {key:?}"
            );
        }

        assert_eq!(key_to_code(&Key::Unknown(1)), None);
    }
}
