create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default '新朋友'
    check (char_length(btrim(nickname)) between 1 and 30),
  friend_code text not null unique
    check (friend_code ~ '^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8}$'),
  message_preview_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  user_low uuid generated always as (least(sender_id, receiver_id)) stored,
  user_high uuid generated always as (greatest(sender_id, receiver_id)) stored,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (sender_id <> receiver_id)
);

create unique index if not exists friend_requests_one_pending_pair
  on public.friend_requests(user_low, user_high)
  where status = 'pending';
create index if not exists friend_requests_receiver_status
  on public.friend_requests(receiver_id, status, created_at desc);
create index if not exists friend_requests_sender_status
  on public.friend_requests(sender_id, status, created_at desc);

create table if not exists public.friendships (
  user_low uuid not null references public.profiles(id) on delete cascade,
  user_high uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_low, user_high),
  check (user_low < user_high)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_low uuid not null references public.profiles(id) on delete cascade,
  user_high uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_low, user_high),
  check (user_low < user_high)
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  last_seen_message_id bigint,
  cleared_through_message_id bigint,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create index if not exists conversation_members_user
  on public.conversation_members(user_id, conversation_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_id_desc
  on public.messages(conversation_id, id desc);

create table if not exists public.friend_lookup_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  attempted_at timestamptz not null default now()
);

create index if not exists friend_lookup_attempts_user_time
  on public.friend_lookup_attempts(user_id, attempted_at desc);

create or replace function public.generate_friend_code()
returns text
language plpgsql
volatile
security definer
set search_path = pg_catalog, public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  index_value integer;
begin
  loop
    candidate := '';
    for index_value in 1..8 loop
      candidate := candidate || substr(
        alphabet,
        1 + (get_byte(extensions.gen_random_bytes(1), 0) % char_length(alphabet)),
        1
      );
    end loop;
    exit when not exists (
      select 1 from public.profiles where friend_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  loop
    begin
      insert into public.profiles(id, nickname, friend_code)
      values (new.id, '新朋友', public.generate_friend_code())
      on conflict (id) do nothing;
      return new;
    exception when unique_violation then
      -- A friend-code collision is harmless; generate another one.
    end;
  end loop;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles(id, nickname, friend_code)
select users.id, '新朋友', public.generate_friend_code()
from auth.users as users
where not exists (select 1 from public.profiles where profiles.id = users.id);

create or replace function public.lock_user_pair(left_user uuid, right_user uuid)
returns void
language sql
security definer
set search_path = pg_catalog, public
as $$
  select pg_advisory_xact_lock(
    hashtextextended(
      least(left_user, right_user)::text || ':' || greatest(left_user, right_user)::text,
      0
    )
  );
$$;

create or replace function public.update_profile(
  p_nickname text,
  p_message_preview_enabled boolean
)
returns public.profiles
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_id uuid := auth.uid();
  updated_profile public.profiles;
begin
  if current_id is null then raise exception '请先登录'; end if;
  if char_length(btrim(coalesce(p_nickname, ''))) not between 1 and 30 then
    raise exception '昵称需要 1-30 个字符';
  end if;
  update public.profiles
  set nickname = btrim(p_nickname),
      message_preview_enabled = coalesce(p_message_preview_enabled, false),
      updated_at = now()
  where id = current_id
  returning * into updated_profile;
  return updated_profile;
end;
$$;

create or replace function public.regenerate_friend_code()
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_id uuid := auth.uid();
  next_code text;
begin
  if current_id is null then raise exception '请先登录'; end if;
  loop
    begin
      next_code := public.generate_friend_code();
      update public.profiles
      set friend_code = next_code, updated_at = now()
      where id = current_id;
      return next_code;
    exception when unique_violation then
      -- Retry the rare race where another transaction took this code.
    end;
  end loop;
end;
$$;

create or replace function public.send_friend_request(p_friend_code text)
returns table(request_id bigint, friend_id uuid, nickname text)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_id uuid := auth.uid();
  target_id uuid;
  target_nickname text;
  created_id bigint;
begin
  if current_id is null then raise exception '请先登录'; end if;
  perform pg_advisory_xact_lock(
    hashtextextended('friend-code:' || current_id::text, 0)
  );
  delete from public.friend_lookup_attempts
  where user_id = current_id and attempted_at <= now() - interval '24 hours';
  if (
    select count(*) from public.friend_lookup_attempts
    where user_id = current_id and attempted_at > now() - interval '10 minutes'
  ) >= 20 then
    raise exception '请求过于频繁，请稍后再试';
  end if;

  insert into public.friend_lookup_attempts(user_id) values (current_id);
  select profiles.id, profiles.nickname
  into target_id, target_nickname
  from public.profiles
  where friend_code = upper(btrim(coalesce(p_friend_code, '')))
    and profiles.id <> current_id;

  if target_id is null then return; end if;
  perform public.lock_user_pair(current_id, target_id);

  if exists (
    select 1 from public.blocks
    where (blocker_id = current_id and blocked_id = target_id)
       or (blocker_id = target_id and blocked_id = current_id)
  ) or exists (
    select 1 from public.friendships
    where user_low = least(current_id, target_id)
      and user_high = greatest(current_id, target_id)
  ) then
    return;
  end if;

  insert into public.friend_requests(sender_id, receiver_id)
  values (current_id, target_id)
  on conflict do nothing
  returning id into created_id;
  if created_id is null then return; end if;

  return query select created_id, target_id, target_nickname;
end;
$$;

create or replace function public.respond_friend_request(
  p_request_id bigint,
  p_accept boolean
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_id uuid := auth.uid();
  request_row public.friend_requests;
  created_conversation_id uuid;
begin
  if current_id is null then raise exception '请先登录'; end if;
  select * into request_row
  from public.friend_requests
  where id = p_request_id;

  if request_row.id is null
    or request_row.receiver_id <> current_id
    or request_row.status <> 'pending' then
    raise exception '好友申请已失效';
  end if;

  perform public.lock_user_pair(request_row.sender_id, request_row.receiver_id);
  select * into request_row
  from public.friend_requests
  where id = p_request_id
  for update;
  if request_row.id is null
    or request_row.receiver_id <> current_id
    or request_row.status <> 'pending' then
    raise exception '好友申请已失效';
  end if;
  if not coalesce(p_accept, false) then
    update public.friend_requests
    set status = 'rejected', responded_at = now()
    where id = request_row.id;
    return null;
  end if;

  if exists (
    select 1 from public.blocks
    where (blocker_id = request_row.sender_id and blocked_id = request_row.receiver_id)
       or (blocker_id = request_row.receiver_id and blocked_id = request_row.sender_id)
  ) then
    raise exception '好友申请已失效';
  end if;

  insert into public.friendships(user_low, user_high)
  values (request_row.user_low, request_row.user_high)
  on conflict (user_low, user_high) do nothing;

  insert into public.conversations(user_low, user_high)
  values (request_row.user_low, request_row.user_high)
  on conflict (user_low, user_high)
  do update set user_low = excluded.user_low
  returning id into created_conversation_id;

  insert into public.conversation_members(conversation_id, user_id)
  values
    (created_conversation_id, request_row.user_low),
    (created_conversation_id, request_row.user_high)
  on conflict (conversation_id, user_id) do nothing;

  update public.friend_requests
  set status = 'accepted', responded_at = now()
  where id = request_row.id;
  return created_conversation_id;
end;
$$;

create or replace function public.remove_friend(p_friend_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare current_id uuid := auth.uid();
begin
  if current_id is null or p_friend_id is null or p_friend_id = current_id then
    raise exception '好友不存在';
  end if;
  perform public.lock_user_pair(current_id, p_friend_id);
  delete from public.friendships
  where user_low = least(current_id, p_friend_id)
    and user_high = greatest(current_id, p_friend_id);
  update public.friend_requests
  set status = 'cancelled', responded_at = now()
  where user_low = least(current_id, p_friend_id)
    and user_high = greatest(current_id, p_friend_id)
    and status = 'pending';
end;
$$;

create or replace function public.block_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare current_id uuid := auth.uid();
begin
  if current_id is null or p_user_id is null or p_user_id = current_id then
    raise exception '无法拉黑该用户';
  end if;
  perform public.lock_user_pair(current_id, p_user_id);
  insert into public.blocks(blocker_id, blocked_id)
  values (current_id, p_user_id)
  on conflict (blocker_id, blocked_id) do nothing;
  delete from public.friendships
  where user_low = least(current_id, p_user_id)
    and user_high = greatest(current_id, p_user_id);
  update public.friend_requests
  set status = 'cancelled', responded_at = now()
  where user_low = least(current_id, p_user_id)
    and user_high = greatest(current_id, p_user_id)
    and status = 'pending';
end;
$$;

create or replace function public.unblock_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare current_id uuid := auth.uid();
begin
  if current_id is null or p_user_id is null or p_user_id = current_id then
    raise exception '无法解除拉黑';
  end if;
  perform public.lock_user_pair(current_id, p_user_id);
  delete from public.blocks
  where blocker_id = current_id and blocked_id = p_user_id;
end;
$$;

create or replace function public.send_message(
  p_conversation_id uuid,
  p_body text
)
returns public.messages
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_id uuid := auth.uid();
  conversation_row public.conversations;
  friend_id uuid;
  created_message public.messages;
begin
  if current_id is null then raise exception '请先登录'; end if;
  if char_length(btrim(coalesce(p_body, ''))) not between 1 and 500 then
    raise exception '消息需要 1-500 个字符';
  end if;

  select * into conversation_row
  from public.conversations
  where id = p_conversation_id
    and current_id in (user_low, user_high);
  if conversation_row.id is null then raise exception '会话不存在'; end if;
  friend_id := case
    when conversation_row.user_low = current_id then conversation_row.user_high
    else conversation_row.user_low
  end;

  perform public.lock_user_pair(current_id, friend_id);
  if not exists (
    select 1 from public.friendships
    where user_low = least(current_id, friend_id)
      and user_high = greatest(current_id, friend_id)
  ) or exists (
    select 1 from public.blocks
    where (blocker_id = current_id and blocked_id = friend_id)
       or (blocker_id = friend_id and blocked_id = current_id)
  ) then
    raise exception '当前无法发送消息';
  end if;

  insert into public.messages(conversation_id, sender_id, body)
  values (p_conversation_id, current_id, btrim(p_body))
  returning * into created_message;
  return created_message;
end;
$$;

create or replace function public.mark_conversation_seen(p_conversation_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  highest_id bigint;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  perform 1 from public.conversation_members
  where conversation_id = p_conversation_id and user_id = auth.uid()
  for update;
  if not found then raise exception '会话不存在'; end if;
  select max(id) into highest_id
  from public.messages where conversation_id = p_conversation_id;
  if highest_id is null then return; end if;
  update public.conversation_members
  set last_seen_message_id = greatest(
    coalesce(last_seen_message_id, 0),
    highest_id
  )
  where conversation_id = p_conversation_id and user_id = auth.uid();
end;
$$;

create or replace function public.clear_conversation(p_conversation_id uuid)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare highest_id bigint;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  perform 1 from public.conversation_members
  where conversation_id = p_conversation_id and user_id = auth.uid()
  for update;
  if not found then raise exception '会话不存在'; end if;
  select max(id) into highest_id
  from public.messages where conversation_id = p_conversation_id;
  if highest_id is not null then
    update public.conversation_members
    set cleared_through_message_id = greatest(
          coalesce(cleared_through_message_id, 0), highest_id
        ),
        last_seen_message_id = greatest(
          coalesce(last_seen_message_id, 0), highest_id
        )
    where conversation_id = p_conversation_id and user_id = auth.uid();
  end if;
  return highest_id;
end;
$$;

create or replace function public.list_blocked_users()
returns table(user_id uuid, nickname text, blocked_at timestamptz)
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select blocks.blocked_id, profiles.nickname, blocks.created_at
  from public.blocks
  join public.profiles on profiles.id = blocks.blocked_id
  where blocks.blocker_id = auth.uid()
  order by blocks.created_at desc;
$$;

create or replace function public.list_friend_requests()
returns table(
  request_id bigint,
  direction text,
  user_id uuid,
  nickname text,
  status text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select requests.id,
    case when requests.receiver_id = auth.uid() then 'incoming' else 'outgoing' end,
    case when requests.receiver_id = auth.uid() then requests.sender_id else requests.receiver_id end,
    profiles.nickname,
    requests.status,
    requests.created_at
  from public.friend_requests as requests
  join public.profiles as profiles
    on profiles.id = case
      when requests.receiver_id = auth.uid() then requests.sender_id
      else requests.receiver_id
    end
  where auth.uid() in (requests.sender_id, requests.receiver_id)
    and requests.status = 'pending'
  order by requests.created_at desc;
$$;

drop function if exists public.get_conversation_summaries();
create function public.get_conversation_summaries()
returns table(
  conversation_id uuid,
  friend_id uuid,
  nickname text,
  last_message_id bigint,
  last_message_body text,
  last_message_at timestamptz,
  unread_count bigint,
  cleared_through_message_id bigint,
  can_message boolean
)
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select conversations.id,
    friend_profile.id,
    friend_profile.nickname,
    latest.id,
    latest.body,
    latest.created_at,
    (
      select count(*)
      from public.messages as unread
      where unread.conversation_id = conversations.id
        and unread.sender_id <> auth.uid()
        and unread.id > coalesce(members.last_seen_message_id, 0)
        and unread.id > coalesce(members.cleared_through_message_id, 0)
    ),
    members.cleared_through_message_id,
    exists (
      select 1 from public.friendships
      where user_low = conversations.user_low and user_high = conversations.user_high
    ) and not exists (
      select 1 from public.blocks
      where (blocker_id = conversations.user_low and blocked_id = conversations.user_high)
         or (blocker_id = conversations.user_high and blocked_id = conversations.user_low)
    )
  from public.conversation_members as members
  join public.conversations as conversations on conversations.id = members.conversation_id
  join public.profiles as friend_profile on friend_profile.id = case
    when conversations.user_low = auth.uid() then conversations.user_high
    else conversations.user_low
  end
  left join lateral (
    select messages.id, messages.body, messages.created_at
    from public.messages
    where messages.conversation_id = conversations.id
      and messages.id > coalesce(members.cleared_through_message_id, 0)
    order by messages.id desc
    limit 1
  ) as latest on true
  where members.user_id = auth.uid()
  order by latest.id desc nulls last, conversations.created_at desc;
$$;

alter table public.profiles enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.blocks enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.friend_lookup_attempts enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (
  id = auth.uid()
  or exists (
    select 1 from public.friendships
    where user_low = least(auth.uid(), profiles.id)
      and user_high = greatest(auth.uid(), profiles.id)
  )
  or exists (
    select 1 from public.friend_requests
    where auth.uid() in (sender_id, receiver_id)
      and profiles.id in (sender_id, receiver_id)
      and status = 'pending'
  )
  or exists (
    select 1 from public.conversations
    where auth.uid() in (user_low, user_high)
      and profiles.id in (user_low, user_high)
  )
);

drop policy if exists friend_requests_select on public.friend_requests;
create policy friend_requests_select on public.friend_requests for select to authenticated
using (auth.uid() in (sender_id, receiver_id));

drop policy if exists friendships_select on public.friendships;
create policy friendships_select on public.friendships for select to authenticated
using (auth.uid() in (user_low, user_high));

drop policy if exists blocks_select on public.blocks;
create policy blocks_select on public.blocks for select to authenticated
using (blocker_id = auth.uid());

drop policy if exists conversations_select on public.conversations;
create policy conversations_select on public.conversations for select to authenticated
using (auth.uid() in (user_low, user_high));

drop policy if exists conversation_members_select on public.conversation_members;
create policy conversation_members_select on public.conversation_members for select to authenticated
using (user_id = auth.uid());

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select to authenticated
using (
  exists (
    select 1 from public.conversation_members
    where conversation_id = messages.conversation_id
      and user_id = auth.uid()
      and messages.id > coalesce(cleared_through_message_id, 0)
  )
);

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.friend_requests from anon, authenticated;
revoke all on table public.friendships from anon, authenticated;
revoke all on table public.blocks from anon, authenticated;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.conversation_members from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
revoke all on table public.friend_lookup_attempts from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.friend_requests to authenticated;
grant select on table public.friendships to authenticated;
grant select on table public.blocks to authenticated;
grant select on table public.conversations to authenticated;
grant select on table public.conversation_members to authenticated;
grant select on table public.messages to authenticated;

revoke execute on function public.generate_friend_code() from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.lock_user_pair(uuid, uuid) from public;

revoke execute on function public.update_profile(text, boolean) from public;
revoke execute on function public.regenerate_friend_code() from public;
revoke execute on function public.send_friend_request(text) from public;
revoke execute on function public.respond_friend_request(bigint, boolean) from public;
revoke execute on function public.remove_friend(uuid) from public;
revoke execute on function public.block_user(uuid) from public;
revoke execute on function public.unblock_user(uuid) from public;
revoke execute on function public.send_message(uuid, text) from public;
revoke execute on function public.mark_conversation_seen(uuid) from public;
revoke execute on function public.clear_conversation(uuid) from public;
revoke execute on function public.list_friend_requests() from public;
revoke execute on function public.list_blocked_users() from public;
revoke execute on function public.get_conversation_summaries() from public;

grant execute on function public.update_profile(text, boolean) to authenticated;
grant execute on function public.regenerate_friend_code() to authenticated;
grant execute on function public.send_friend_request(text) to authenticated;
grant execute on function public.respond_friend_request(bigint, boolean) to authenticated;
grant execute on function public.remove_friend(uuid) to authenticated;
grant execute on function public.block_user(uuid) to authenticated;
grant execute on function public.unblock_user(uuid) to authenticated;
grant execute on function public.send_message(uuid, text) to authenticated;
grant execute on function public.mark_conversation_seen(uuid) to authenticated;
grant execute on function public.clear_conversation(uuid) to authenticated;
grant execute on function public.list_friend_requests() to authenticated;
grant execute on function public.list_blocked_users() to authenticated;
grant execute on function public.get_conversation_summaries() to authenticated;

alter table public.messages replica identity full;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end;
$$;
